### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by mindrunner** [bojleros/megacli2prom#1]
Hi
do you visualize the Data somewhere? I am planning to create a grafana dashboard for it. (If nothing like this exist yet?)

Cheers

**Comment by eil2017** [comment]
Came here to check for the same thing - ever get one built?

**Comment by mindrunner** [comment]
Not really. I had to abandon the controller. Moved from hw-RAID to md-linux-raid. However, the server is not physically accessible for me right now and it has some problems with random lockups. So not working on this at the moment.

**Comment by bojleros** [comment]
Hi @mindrunner

I have not planned to make any dedicated dashboard since the only data that is suposed to change is temperature and I have it embedded into another chart. Apart of that i am more interested in getting alert in event of dg degradation instead. In such case you will have to inspect directly so dashboards again have limited usage.

**Comment by mindrunner** [comment]
Thanks for getting back here. I think we can close this due to lack of interest :)
